### ISSUE TITLE
Bug: The openim-server-openim-msgtransfer-54c6d5d5-8pxvx and Openim-server-Openim-Pus-79C7768D89-7rdTM Pods restart indefinitely  

### ISSUE THREAD

**Issue by hlovingness** [openimsdk/helm-charts#8]
```
configFolderPath: 
use config ../config/config.yaml
use config ../config/notification.yaml
PortFromConfig: prometheus_port
RootCmd.GetPortFromConfig: prometheus_port
2023-10-27 16:21:22.166 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.179909(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.167 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.739645(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.169 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.981042(ms)", "sql": "SELECT count(*) FROM information_schema.tables WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND table_type = 'BASE TABLE'"}
2023-10-27 16:21:22.169 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.175881(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.170 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.693231(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.170 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.239424(ms)", "sql": "SELECT * FROM `chat_logs` LIMIT 1"}
2023-10-27 16:21:22.171 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "1.190610(ms)", "sql": "SELECT column_name, column_default, is_nullable = 'YES', data_type, character_maximum_length, column_type, column_key, extra, column_comment, numeric_precision, numeric_scale , datetime_precision FROM information_schema.columns WHERE table_schema = 'openim' AND table_name = 'chat_logs' ORDER BY ORDINAL_POSITION"}
2023-10-27 16:21:22.172 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.181524(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.172 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.591284(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.173 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.890513(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'sendTime'"}
2023-10-27 16:21:22.174 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.164014(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.174 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.570112(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.175 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.816590(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'send_id'"}
2023-10-27 16:21:22.176 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.222836(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.176 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.624001(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.177 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.804750(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'recv_id'"}
2023-10-27 16:21:22.178 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.167356(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.178 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.598151(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.179 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.851954(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'session_type'"}
2023-10-27 16:21:22.180 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.181713(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.180 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.614439(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.182 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.838816(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'session_type_alone'"}
2023-10-27 16:21:22.182 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.204947(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.183 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.631816(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.184 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.803997(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'content_type'"}
2023-10-27 16:21:22.184 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.176506(ms)", "sql": "SELECT DATABASE()"}
2023-10-27 16:21:22.185 DEBUG [PID:1] msgTransfer [log/sql_logger.go:86] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.591860(ms)", "rows": 1, "sql": "SELECT SCHEMA_NAME from Information_schema.SCHEMATA where SCHEMA_NAME LIKE 'openim%' ORDER BY SCHEMA_NAME='openim' DESC,SCHEMA_NAME limit 1"}
2023-10-27 16:21:22.186 DEBUG [PID:1] msgTransfer [log/sql_logger.go:84] sql exec detail {"gorm": "/app/internal/msgtransfer/init.go:48", "elapsed time": "0.809862(ms)", "sql": "SELECT count(*) FROM information_schema.statistics WHERE table_schema = 'openim' AND table_name = 'chat_logs' AND index_name = 'content_type_alone'"}
mongo: mongodb://root:xx@mongodb.mongo.svc.cluster.local:27017/openim?maxPoolSize=100&authSource=admin
start msg transfer prometheusPort: 0
2023-10-27 16:21:22.220 DEBUG [PID:1] msgTransfer [kafka/consumer_group.go:66] register consumer group {"groupID": "mongo"}
2023-10-27 16:21:22.220 DEBUG [PID:1] msgTransfer [kafka/consumer_group.go:66] register consumer group {"groupID": "redis"}
panic: kafka server: Offset's topic has not yet been created
goroutine 251 [running]:
github.com/openimsdk/open-im-server/v3/pkg/common/kafka.(*MConsumerGroup).RegisterHandleAndConsumer(0xc000596380, {0x1717de0, 0xc0005ca700})
 /app/pkg/common/kafka/consumer_group.go:71 +0x145
created by github.com/openimsdk/open-im-server/v3/internal/msgtransfer.(*MsgTransfer).Start
 /app/internal/msgtransfer/init.go:116 +0x197
```

**Comment by cubxxw** [comment]
Has this issue been resolved at this time?

**Comment by skiffer-git** [comment]
Undergoing comprehensive testing, awaiting updates
